---
- name: Remove /etc/network
  file:
    path: /etc/network
    state: absent

- name: Disable networking
  service:
    name: networking
    state: stopped
    enabled: no

- name: remove /etc/systemd/network
  file:
    path: /etc/systemd/network
    state: absent

- name: create /etc/systemd/network
  file:
    path: /etc/systemd/network
    state: directory


- name: Generate eth0 network
  template:
    src: eth0.network
    dest: /etc/systemd/network/eth0.network
    mode: 0644

- name: Enable systemd-networkd
  service:
    name: systemd-networkd
    state: restarted
    enabled: yes

- name: Enable systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
    enabled: yes
